[package]
compiler = "0.14.2" # TODO: check
name = "dhbw-oderso"
version = "1.0.0"
entrypoint = "template/lib.typ"
authors = ["dhbw-typst - a group of motivated DHBW students"]
license = "MIT"
description = "All kinds of theses at DHBW"
repository = "https://github.com/dhbw-typst/oderso-template-dev"
keywords = [
    "DHBW",
    "template",
    "Praxisarbeit",
    "Studienarbeit",
    "Bachelorarbeit",
    "Bachelor's Thesis",
    "Bachelor",
    "Final Thesis",
    "IHK",
    "Praxisbericht",
]
categories = ["thesis", "layout"]
disciplines = ["engineering", "computer-science"]

[template]
path = "template"               # TODO: check
entrypoint = "main-dhbw-ka.typ"
thumbnail = "thumbnail.png"
