name: Code Analysis
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install typstyle
        run: |
          curl -L https://github.com/typstyle-rs/typstyle/releases/download/v0.14.4/typstyle-x86_64-unknown-linux-gnu -o typstyle
          chmod +x typstyle
      - name: Typstyle version
        run: ./typstyle --version
      - name: Run formatting check
        run: |
          ./typstyle ./template --check
  check_build:
    name: Check Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          mkdir -p typst_bin
          tar -xf typst.tar.xz -C typst_bin
          mv typst_bin/typst-x86_64-unknown-linux-musl/typst typst
          chmod +x typst
      - name: Typst version
        run: ./typst --version
      - name: Build template
        run: |
          for file in $(ls template/main-*.typ); do
            ./typst compile $file
          done
          ./typst compile documentation.typ

  # needs to be rewritten for every program's main-file

#   check_pdf:
#     name: Check PDF parity
#     permissions:
#       pull-requests: write
#     steps:
#       - name: Checkout PR branch
#         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
#         with:
#           path: new
#       - name: Install typst
#         run: |
#           curl -L https://github.com/typst/typst/releases/download/v0.14.2/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
#           mkdir -p typst_bin
#           tar -xf typst.tar.xz -C typst_bin
#           mv typst_bin/typst-x86_64-unknown-linux-musl/typst typst
#           chmod +x typst
#       - name: Typst version
#         run: ./typst --version
#       - name: Build PDF on PR branch
#         run: |
#           ./typst compile new/template/main.typ new.pdf
#       - name: Checkout main branch
#         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
#         with:
#           ref: main
#           path: old
#       - name: Build PDF on main branch
#         run: |
#           ./typst compile old/template/main.typ old.pdf
#       - name: Compare PDFs
#         id: diff_check
#         uses: nowsprinting/diff-pdf-action@21193e71055e9cd98ae8704bf95590e50fb0d3c3 # v1.2.3
#         continue-on-error: true
#         with:
#           file1: old.pdf
#           file2: new.pdf
#           options: --skip-identical --mark-differences --output-diff=diff.pdf
#           suppress-diff-error: false
#       - name: Upload diff.pdf artifact
#         id: upload_diff
#         if: steps.diff_check.outcome == 'failure'
#         uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 #v3.2.1
#         with:
#           name: diff-pdf
#           path: diff.pdf
#       - name: Comment on PR with artifact link
#         if: steps.diff_check.outcome == 'failure' && github.event_name == 'pull_request'
#         uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
#         with:
#           script: |
#             github.rest.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: `> [!NOTE]
#             > **PDF Differences Detected:** The PDF output has changed between the main branch and this PR.
#             > **Download the diff:** Go to the [Actions tab](${context.payload.repository.html_url}/actions/runs/${context.runId}) and download the \`diff-pdf\` artifact.`
#             })
#       - name: Fail workflow if PDFs differ
#         if: steps.diff_check.outcome == 'failure' && startsWith(github.event.pull_request.head.ref, 'renovate/')
#         run: |
#           echo "PDF differences detected between main branch and PR"
#           exit 1
